# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(996, 589)
        self.ConnectButton = QtWidgets.QPushButton(Dialog)
        self.ConnectButton.setGeometry(QtCore.QRect(0, 10, 88, 31))
        self.ConnectButton.setDefault(True)
        self.ConnectButton.setObjectName("ConnectButton")
        self.sendButton = QtWidgets.QPushButton(Dialog)
        self.sendButton.setGeometry(QtCore.QRect(0, 520, 88, 27))
        self.sendButton.setObjectName("sendButton")
        self.MainDisplayTextEdit = QtWidgets.QTextEdit(Dialog)
        self.MainDisplayTextEdit.setGeometry(QtCore.QRect(10, 50, 731, 411))
        self.MainDisplayTextEdit.setReadOnly(True)
        self.MainDisplayTextEdit.setObjectName("MainDisplayTextEdit")
        self.MessagesTextEdit = QtWidgets.QTextEdit(Dialog)
        self.MessagesTextEdit.setGeometry(QtCore.QRect(750, 10, 241, 201))
        self.MessagesTextEdit.setReadOnly(True)
        self.MessagesTextEdit.setObjectName("MessagesTextEdit")
        self.CharactersTextEdit = QtWidgets.QTextEdit(Dialog)
        self.CharactersTextEdit.setGeometry(QtCore.QRect(750, 220, 241, 191))
        self.CharactersTextEdit.setReadOnly(True)
        self.CharactersTextEdit.setObjectName("CharactersTextEdit")
        self.AvailableRoomsTextEdit = QtWidgets.QTextEdit(Dialog)
        self.AvailableRoomsTextEdit.setGeometry(QtCore.QRect(750, 420, 241, 161))
        self.AvailableRoomsTextEdit.setReadOnly(True)
        self.AvailableRoomsTextEdit.setObjectName("AvailableRoomsTextEdit")
        self.PlayerStatsTextEdit = QtWidgets.QTextEdit(Dialog)
        self.PlayerStatsTextEdit.setGeometry(QtCore.QRect(460, 470, 271, 111))
        self.PlayerStatsTextEdit.setReadOnly(True)
        self.PlayerStatsTextEdit.setObjectName("PlayerStatsTextEdit")
        self.InstructionTextEdit = QtWidgets.QTextEdit(Dialog)
        self.InstructionTextEdit.setGeometry(QtCore.QRect(10, 470, 271, 41))
        self.InstructionTextEdit.setReadOnly(True)
        self.InstructionTextEdit.setObjectName("InstructionTextEdit")
        self.port_input = QtWidgets.QLineEdit(Dialog)
        self.port_input.setGeometry(QtCore.QRect(90, 10, 271, 31))
        self.port_input.setObjectName("port_input")
        self.General_input = QtWidgets.QLineEdit(Dialog)
        self.General_input.setGeometry(QtCore.QRect(100, 520, 191, 31))
        self.General_input.setObjectName("General_input")
        self.QuitButton = QtWidgets.QPushButton(Dialog)
        self.QuitButton.setGeometry(QtCore.QRect(610, 10, 111, 31))
        self.QuitButton.setObjectName("QuitButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ConnectButton.setText(_translate("Dialog", "Connect"))
        self.sendButton.setText(_translate("Dialog", "send"))
        self.MessagesTextEdit.setPlaceholderText(_translate("Dialog", "Messages appear here"))
        self.CharactersTextEdit.setPlaceholderText(_translate("Dialog", "Present characters appear here"))
        self.AvailableRoomsTextEdit.setPlaceholderText(_translate("Dialog", "Available rooms appear here"))
        self.PlayerStatsTextEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Sans\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">playerName:  | ⚔ ATK:  | ⛨ DEF:  ││ ✨ REG:  | ♥ HP: ││ Gold:  | Cur Rm:    </p></body></html>"))
        self.PlayerStatsTextEdit.setPlaceholderText(_translate("Dialog", "Player stats should appear here"))
        self.InstructionTextEdit.setPlaceholderText(_translate("Dialog", "Instructions appear here"))
        self.QuitButton.setText(_translate("Dialog", "Quit"))
